language: ruby
rvm:
- 2.3.3
script:
- "./scripts/build"
- "./scripts/test"
branches:
  only:
  - master
  - "/master-(.*)/"
before_deploy:
- openssl aes-256-cbc -K $encrypted_550be8be9cea_key -iv $encrypted_550be8be9cea_iv
  -in keypair.pem.enc -out keypair.pem -d
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy
  on:
    branch: master
