language: ruby
rvm:
- 2.4.5
install:
  - bundle install --jobs=3 --retry=3 --full-index --deployment
script:
- "./scripts/build"
- "./scripts/test"
branches:
  only:
  - master
  - "/master-(.*)/"
before_deploy:
- openssl aes-256-cbc -K $encrypted_550be8be9cea_key -iv $encrypted_550be8be9cea_iv
  -in keypair.pem.enc -out keypair.pem -d
- bundle exec jekyll build --config _config_production.yml,_config.yml
- export JEKYLL_ENV=production
- chmod 600 ./keypair.pem
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy
  on:
    branch: master
after_deploy:
  - rm ./keypair.pem
