# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jaysinh's own heed
email: jaysinhp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Full-stack developer by profession, Computer scientist by heart
  and an Actor by gene. I write mostly on programming topics. Browse through
  my blog posts to identify my taste of writing.

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jaysinhp
github_username:  ultimatecoder

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

google_analytics: UA-57792488-6
defaults:
  -
    scope:
      path: ""
    values:
      author: "Jaysinh Shukla"
social:
  name: Jaysinh Shukla
  links:
    - https://twitter.com/jaysinhp
    - https://www.facebook.com/jaysinhp
    - https://github.com/ultimatecoder
    - https://www.goodreads.com/user/show/54554593-jaysinh-shukla
    - https://www.slideshare.net/jaysinhp/
    - https://plus.google.com/u/0/+Jaysinhshukla
google_site_verification: jdvcEp-mfuzvoTr5Z2hwwAYK96cx6zvFocYI1FJ2Gto
